resources:
- name: docker101
  type: git
  source:
    uri: https://github.com/warroyo/docker101
    branch: master

- name: basic-image
  type: docker-image
  source:
    username: ((harbor-username))
    password: ((harbor-password))
    repository: harbor.gcp.59s.io/59s/basic-example
    tag: 1.0.0
    
jobs:
- name: publish
  public: true
  serial: true
  plan:
  - get: docker101
  - put: basic-image
    params:
      build: docker101/examples/basic
